version: "3.5"
services:
  microservices-dev:
    container_name: microservices
    hostname: microservices.local
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 9900:80
    volumes:
      - ".:/var/www"
    env_file:
      - docker/env/.env
  neo4j:
    image: neo4j:latest
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import
  redis:
    container_name: redis
    image: redis:latest
networks:
  default:
    name: core-network
